### PR TITLE
resolves dodie/scott#90

### PR DESCRIPTION
**Pull request by balazsmiklos85**

### CODE REVIEW

**Comment by dodie** [comment]
Hi @balazsmiklos85 !

Thank you for your contribution!
I've tried to run the modified JUnit test suite with Java 13, but I got the following error:

```
java.lang.IllegalArgumentException: Unsupported class file major version 57
```

The Java version I have:

```
» java --version
openjdk 13 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)
```

To get the error, I ran the following command on the root project:
```
mvn clean install
```

I think Java 13 might use a new bytecode version, not supported by the [currently used 7.0 ASM](https://github.com/dodie/scott/blob/master/scott/pom.xml#L132-L141) library. According to the [ASM release log](https://asm.ow2.io/versions.html), the latest [7.2](https://mvnrepository.com/artifact/org.ow2.asm/asm/7.2) should support Java 13 (and 14) bytecodes.

If you can reproduce the error in your environment, could you please also try this new ASM version?

Thank you,
David

**Comment by dodie** [comment]
I've just checked the build with the upgraded dependencies on Ubuntu 16.04.6 LTS, for me it solved the issue. (Added a commit to your branch with these changes.)
Could you please double-check if this commit fixes the problem in your environment? If not, what OS are you using?

Thanks!

**Comment by dodie** [comment]
Hm, seems like once this issue is resolved, there will be another to deal with, as Azure Pipelines currently does not support Java 13. One more reason for docker based builds (#93)...

**Comment by balazsmiklos85** [comment]
Apparently my issue was that even though I had Java 13 and used it successfully before, Maven somehow decided to use Java 8 instead because it was installed for another project. One more reason for docker based builds :)

**Comment by dodie** [comment]
The new pipeline is in place, so the build works with the new Java version. Thanks for the changes, @balazsmiklos85 !

**Pull request merged**
