### PR TITLE
https://github.com/damianszczepanik/cucumber-reporting

### PR DESCRIPTION
**Pull request by basalt79**
This will solve the ticket Record whole scenarios with Cucumber #12

in addition to 

- html
- console
- json
- i added a plugin that will generate also html based on the json file, to the verification becomes more easy (https://github.com/damianszczepanik/cucumber-reporting)

### CODE REVIEW

**Comment by dodie** [comment]
The PR contains these two commits as well as the commit containing your changes:

- 43d9b08: Revert "Improve loop rendering 18"
- e10004b: Revert "Improve loop rendering 18"

The tests are failing in your branch due to a compilation error, most likely related to these commits. (If I revert them, the test suite passes.) Are these commits contain something related to this PR? If not, could you remove/revert these commits?

After reverting the commits I've briefly tested the cucumber example project with your modifications. The error report looks cool, now it indeed contains previous steps, so now can follow through the details of every step involved. However, for me, it does not display the actual failing step. For the failing *Repeating an operation* scenario I see the following report:

```
 15|      @Given("^a Calculator")
  16|      public void a_calculator() throws Throwable {
    |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@7dfd3c81
    |          
  17|          calculator = new Calculator();  // CalculatorSteps.calculator=hu.advancedweb.example.Calculator@4dd6fd0a
  18|      }

  20|      @When("^I enter (\\d+)$")
  21|      public void i_enter_a_number(int number) throws Throwable {
    |          //    => number=5
    |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@4dd6fd0a
    |          
  22|          calculator.enter(number);
  23|      }

  30|      @When("^I press MULTIPLY$")
  31|      public void i_press_MULTIPLY() throws Throwable {
    |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@4dd6fd0a
    |          
  32|          calculator.pressMultiply();
  33|      }

  20|      @When("^I enter (\\d+)$")
  21|      public void i_enter_a_number(int number) throws Throwable {
    |          //    => number=2
    |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@4dd6fd0a
    |          
  22|          calculator.enter(number);
  23|      }

  35|      @Then("^I should see (\\d+)$")
  36|      public void i_should_see_the_result(int number) throws Throwable {
    |          //    => number=10
    |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@4dd6fd0a
    |          
  37|          int result = calculator.getResult();  // result=10
  38|          assertThat(result, equalTo(number));
  39|      }
java.lang.AssertionError: 
Expected: <80>
     but: was <160>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at hu.advancedweb.example.step.CalculatorSteps.i_should_see_the_following_numbers(CalculatorSteps.java:55)
	at ✽.And I should see 20, 40 and 80 if I repeat the operation three times(calculator.feature:16)

```

So the final step included in this report is the last step passed without a failure, the source of the *"And I should see 20, 40 and 80 if I repeat the operation three times"* step is omitted. 

image

Could you look at it what's causing this behavior?

**Comment by basalt79** [comment]
hi, sorry for the failing tests, this should now be ok, i also fixed the missing last step information. can you give it a try

**Comment by dodie** [comment]
Yep, it works fine! I've noticed one minor thing though: for some reason, the exception is not rendered at the final step. From the HTML report:

```

...

  41|      @Then("^I should see (\\d+), (\\d+) and (\\d+) if I repeat the operation three times$")
  42|      public void i_should_see_the_following_numbers(int first, int second, int third) throws Throwable {
    |          //    => first=20
    |          //    => second=40
    |          //    => third=80
    |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@4dd6fd0a
    |          
  43|          calculator.pressEnter();
  44|          int result = calculator.getResult();  // result=[20]
  45|          assertThat(result, equalTo(first));
  46|  
  47|          calculator.pressEnter();
  48|          result = calculator.getResult();  // result=[40]
  49|          assertThat(result, equalTo(second));
  50|          
  51|          calculator.pressEnter();
  52|          // Oops. Accidentally pressing the button twice.
  53|          calculator.pressEnter();
  54|          result = calculator.getResult();  // result=[160]
  55|          assertThat(result, equalTo(third));
  56|      }
java.lang.AssertionError: 
Expected: <80>
     but: was <160>

...

```

At line 55 there should be a note about the exception. Maybe the exception object is not passed to the renderer? Otherwise, it looks fine, I've just checked the code and it looks cool too. :+1: 

Also, I think the other "Revert Improve loop rendering 18" commit (43d9b08) should be reverted as well because it removes a [test](https://github.com/dodie/scott/pull/34/files#diff-666d6c9d0d802f9b1659edb3e63492adL26) and a [fix](https://github.com/dodie/scott/pull/34/files#diff-84149de9b1532cb813d20c83f685c2f2L217) from your previous PR.

**Comment by basalt79** [comment]
i see both html reports with stacktrace
bildschirmfoto vom 2017-10-08 09-37-05
bildschirmfoto vom 2017-10-08 09-36-43

**Comment by dodie** [comment]
In vanilla scott a failing test has star (*) indicator and a comment to indicate the source of the failure (at line 55):

```

...

  52|          // Oops. Accidentally pressing the button twice.
  53|          calculator.pressEnter();
  54|          result = calculator.getResult();  // result=160
  55|*         assertThat(result, equalTo(third));  // AssertionError: Expected: <80>
    |                                               //      but: was <160>
  56|      }
```

However, this indicator is not visible in the enhanced cucumber report: 

```
  52|          // Oops. Accidentally pressing the button twice.
  53|          calculator.pressEnter();
  54|          result = calculator.getResult();  // result=[160]
  55|          assertThat(result, equalTo(third));
  56|      }
``` 

The stack trace after the source code renders for me as well. It's a good idea to keep the stack trace in the report, but I think it would be convenient to display a hint in the code as well, so the user can locate the source of an error easier. Is it possible to add these indicators to the report?

**Comment by basalt79** [comment]
aah now i know whats missing, i have a version where this is also rendered. i will create a new Pull request for this, to also have a clean version on top of the current master.

**Comment by dodie** [comment]
Ok. Can I merge this PR or should I wait for the new one?

**Comment by basalt79** [comment]
Yes i will push a new one, but just to be sure, the "new" output will look like this:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running hu.advancedweb.example.FeatureTest
Feature: Calculator

  Scenario: Add two numbers # calculator.feature:3
    Given a Calculator      # CalculatorSteps.a_calculator()
    When I enter 5          # CalculatorSteps.i_enter_a_number(int)
    And I press PLUS        # CalculatorSteps.i_press_plus()
    And I enter 10          # CalculatorSteps.i_enter_a_number(int)
    Then I should see 15    # CalculatorSteps.i_should_see_the_result(int)

  Scenario: Repeating an operation                                       # calculator.feature:10
    Given a Calculator                                                   # CalculatorSteps.a_calculator()
    When I enter 5                                                       # CalculatorSteps.i_enter_a_number(int)
    And I press MULTIPLY                                                 # CalculatorSteps.i_press_MULTIPLY()
    And I enter 2                                                        # CalculatorSteps.i_enter_a_number(int)
    Then I should see 10                                                 # CalculatorSteps.i_should_see_the_result(int)
    And I should see 20, 40 and 80 if I repeat the operation three times # CalculatorSteps.i_should_see_the_following_numbers(int,int,int)
      
        15|      @Given("^a Calculator")
        16|      public void a_calculator() throws Throwable {
          |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@51891008
          |          
        17|          calculator = new Calculator();  // CalculatorSteps.calculator=[hu.advancedweb.example.Calculator@7354b8c5]
        18|      }
      
        20|      @When("^I enter (\\d+)$")
        21|      public void i_enter_a_number(int number) throws Throwable {
          |          //    => number=5
          |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@7354b8c5
          |          
        22|          calculator.enter(number);
        23|      }
      
        30|      @When("^I press MULTIPLY$")
        31|      public void i_press_MULTIPLY() throws Throwable {
          |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@7354b8c5
          |          
        32|          calculator.pressMultiply();
        33|      }
      
        20|      @When("^I enter (\\d+)$")
        21|      public void i_enter_a_number(int number) throws Throwable {
          |          //    => number=2
          |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@7354b8c5
          |          
        22|          calculator.enter(number);
        23|      }
      
        35|      @Then("^I should see (\\d+)$")
        36|      public void i_should_see_the_result(int number) throws Throwable {
          |          //    => number=10
          |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@7354b8c5
          |          
        37|          int result = calculator.getResult();  // result=[10]
        38|          assertThat(result, equalTo(number));
        39|      }
      
        41|      @Then("^I should see (\\d+), (\\d+) and (\\d+) if I repeat the operation three times$")
        42|      public void i_should_see_the_following_numbers(int first, int second, int third) throws Throwable {
          |          //    => first=20
          |          //    => second=40
          |          //    => third=80
          |          //    => CalculatorSteps.calculator=hu.advancedweb.example.Calculator@7354b8c5
          |          
        43|          calculator.pressEnter();
        44|          int result = calculator.getResult();  // result=[20]
        45|          assertThat(result, equalTo(first));
        46|  
        47|          calculator.pressEnter();
        48|          result = calculator.getResult();  // result=[40]
        49|          assertThat(result, equalTo(second));
        50|          
        51|          calculator.pressEnter();
        52|          // Oops. Accidentally pressing the button twice.
        53|          calculator.pressEnter();
        54|          result = calculator.getResult();  // result=[160]
        55|*         assertThat(result, equalTo(third));  // AssertionError: Expected: <80>
          |                                               //      but: was <160>
        56|      }
      
      	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
      	at org.junit.Assert.assertThat(Assert.java:956)
      	at org.junit.Assert.assertThat(Assert.java:923)
      	at hu.advancedweb.example.step.CalculatorSteps.i_should_see_the_following_numbers(CalculatorSteps.java:55)
      	at ✽.And I should see 20, 40 and 80 if I repeat the operation three times(calculator.feature:16)
      




```

**Comment by dodie** [comment]
Ok, it looks great to me! :)

**Comment by basalt79** [comment]
ok i created a new PR, so the new one should be a clean one.

**Pull request closed without merging**
