### PR TITLE
Gradle plugin

### PR DESCRIPTION
**Pull request by luksrn**
Issue #44 

Please read https://guides.gradle.org/publishing-plugins-to-gradle- plugin-portal /

After configuring your credentials you can publish the plugin locale at scott-gradle-plugin folder

$ ./gradlew tasks

```
Plugin Portal tasks
-------------------
login - Update the gradle.properties files so this machine can publish to the Gradle Plugin portal.
**publishPlugins - Publishes this plugin to the Gradle Plugin portal.**
```

$ ./gradlew publishPlugins
```
> Task :publishPlugins
Publishing plugin hu.advanceweb.scott-plugin version 3.3.3
Publishing artifact build/libs/gradle-3.3.3.jar
Publishing artifact build/libs/gradle-3.3.3-sources.jar
Publishing artifact build/libs/gradle-3.3.3-javadoc.jar
Publishing artifact build/libs/gradle-3.3.3-groovydoc.jar
Publishing artifact build/publish-generated-resources/pom.xml
Activating plugin hu.advanceweb.scott-plugin version 3.3.3
```
To test/approve the PR, I believe you can follow those flow to generate the artifacts and test the changes.

The Junit4 and Junit5 test reports keep detailed information, but only cucumber reports generated by scott.

:brazil:

### CODE REVIEW

**Comment by dodie** [comment]
Hi @luksrn !

Awesome job, thank you! So far I've only had the time to scan the code, but I'll try it soon as well, and merge the PR.

Thanks,
David

**Comment by dodie** [comment]
Hey @luksrn!

I had some time in my hands, so I could take a closer look at your PR (sorry that it took me this long).

I was able to try the plugin locally with the following steps:

1. Build the `scott-gradle-plugin` module.
2. Modify the `build.gradle` in the `scott-examples/junit4` module, to resolve the plugin through a file reference:
```
buildscript{
    dependencies{
        classpath fileTree(dir:'../../scott-gradle-plugin/build/libs', include: ['*.jar'])
    }
}

apply plugin: hu.advanceweb.scott.ScottPlugin
```
3. Execute `./gradlew test` in the `scott-examples/junit4` module.

:+1: **It works nicely** :+1:

The generated HTML report correctly contains the Scott report:
image

And running the tests with `./gradlew test -i` makes this information visible in the console as well:

image

**A few questions:**

- Would it possible to target Java 8 source compatibility in the `scott-gradle-plugin` module? Many projects still use Java 8, I'd prefer to support it for a while.

- I think there is a typo in the groupname of the plugin. Could you please change it from advanceweb to advance**d**web?

Many thanks!

**Comment by luksrn** [comment]
Hey @dodie , how are you, man? I hope you're ok! 

I made the changes that you suggested. Good points.

**Comment by dodie** [comment]
Hey @luksrn! Cool thanks! Thank you for all your effort! The plugin works as expected, and it's implemented really nicely! I'll release it at the end of the month along with a new version of Scott.

**Pull request merged**
